komanda/config/routes.rb
Komanda::Application.routes.draw do

  root :to => 'events#index'
  
  resources :events do
    get :going, on: :member
    get :join, on: :member
    get :rate, on: :member
    get :pictures, on: :member
    resources :comments
  end
  
  resources :suggestions do
    get :star, on: :member
    get :popular, on: :collection
    resources :comments
  end
  
  resources :shares
  
  resources :orders
  
  resources :products
  
  match '/k-stuff' => 'products#index', as: :kstuff
  match '/k-stuff/new' => 'products#new'
  match '/contact' => 'static_pages#contact', as: :contact
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'parties#index'
  match '/signin' => 'sessions#new', as: :signin
  match '/signout' => 'sessions#destroy', as: :signout
end

komanda/app/models/product.rb
class Product
  include Mongoid::Document
  
  field :name,  type: String
  field :price, type: Integer
  field :pictures, type: Array, default: []
  field :num_sold, default: 0
  
  validates_presence_of :name, :price, :pictures
end

komanda/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end
  
  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(params[:product])
    @product.pictures = (params[:product][:pictures]).split(" ")
    
    if @product.save
      redirect_to kstuff_path, notice: "New product added."
    else
      render 'new'
    end
  end
  
  def edit
    @product = Product.find(params[:id])
  end
  
  def update
    @product = Product.find(params[:id])
    @product.update_attributes(params[:product])
    @product.update_attribute(:pictures, params[:product][:pictures].split(" "))
    redirect_to kstuff_path, notice: "Product updated."
  end
  
  def destroy
    Product.find(params[:id]).destroy
    redirect_to kstuff_path, notice: "Product removed."
  end
  
end

komanda/app/helpers/products_helper.rb
module ProductsHelper
end

komanda/app/views/products/_form.html.erb
<%= form_for @product, html: { class: "form-horizontal" } do |f| %>
	
	<% if @product.errors.any? %>
		<div class="alert alert-error">
			<% @product.errors.full_messages.each do |error| %>
				<p><%= error %></p>
			<% end %>
		</div>
	<% end %>
	
	<div class="control-group">
		<div class="control-label"><%= f.label :name, "Name*" %></div>
		<div class="controls">
			<%= f.text_field :name, class: "input-xlarge" %>
		</div>
	</div>
	
	<div class="control-group">
		<div class="control-label"><%= f.label :price, "Price*" %></div>
		<div class="controls">
			<%= f.text_field :price, class: "input-mini" %>
		</div>
	</div>
	
	<div class="control-group">
		<div class="control-label"><%= f.label :pictures, "Pictures*" %></div>
		<div class="controls">
			<%= f.text_area :pictures, rows: 3, value: @product.pictures.join(" ") %>
		</div>
	</div>
	
	<div class="controls">
		<%= f.submit "Add", class: "btn btn-primary" %>
		<%= link_to "Cancel", products_path, class: "btn" %>
	</div>
<% end %>

komanda/app/views/products/_product.html.erb
<%= link_to (current_user ? "#{new_order_path}?product_id=#{product.id}" : signin_path) do %>

	<article class="span4 default product">
		
		<% if admin_user? %>
			<div class="admin">
				<%= link_to "#{new_order_path}?product_id=#{product.id}" do %>
					<i class="icon-shopping-cart"></i>
				<% end %>
				
				<%= link_to edit_product_path(product) do %>
					<i class="icon-edit"></i>
				<% end %>
			
				<%= link_to product,
				 	method: :delete, 
					:data => { :confirm => 'Are you sure you want to delete this product?' } do %>
					<i class="icon-remove"></i>
				<% end %>
			</div>
		<% end %>
	
		<%= image_tag product.pictures.first, class: "main-picture", id: "main-picture-#{product.id}" %>

		<div class="thumbs">
			<% product.pictures.each do |picture| %>
				<%= image_tag picture, size: "50x50", 
					class: "thumb #{'selected' if  picture == product.pictures.first}" %>
			<% end %>
		</div>
	
		<p class="lead muted">
			<%= product.name %>
 
			<span class="price pull-right">$<%= product.price %></span>
		</p>
		
	</article>

<% end %>

komanda/app/views/products/edit.html.erb
<div class="row">
	<div class="offset2 span7 default">
		<h3 class="center">Edit Product</h3>
		
		<%= render 'form' %>
	</div>
</div>

komanda/app/views/products/index.html.erb
<h3>
	K-stuff
	<div class="pull-right facebook" style="width: 90px; height: 30px">
		<div class="fb-like" data-send="false" 
			data-layout="button_count" data-width="450" data-show-faces="true"></div>
	</div>
</h3>

<% if notice %>
	<div class="alert alert-success center">
		<%= notice %>
	</div>
<% end %>

<div class="row">
	<%= render @products %>
</div>

komanda/app/views/products/new.html.erb
<div class="row">
	<div class="offset2 span7 default">
		<h3 class="center">New Product</h3>
		
		<%= render 'form' %>
	</div>
</div>