komanda/config/routes.rb
Komanda::Application.routes.draw do

  root :to => 'events#index'
  
  resources :events do
    get :going, on: :member
    get :join, on: :member
    get :rate, on: :member
    get :pictures, on: :member
    resources :comments
  end
  
  resources :suggestions do
    get :star, on: :member
    get :popular, on: :collection
    resources :comments
  end
  
  resources :shares
  
  resources :orders
  
  resources :products
  
  match '/k-stuff' => 'products#index', as: :kstuff
  match '/k-stuff/new' => 'products#new'
  match '/contact' => 'static_pages#contact', as: :contact
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'parties#index'
  match '/signin' => 'sessions#new', as: :signin
  match '/signout' => 'sessions#destroy', as: :signout
end

komanda/app/models/suggestion.rb
class Suggestion
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActionView::Helpers::SanitizeHelper
  
  scope :recent, desc(:created_at)
  scope :popular, order_by(:star_count.desc, :comment_count.desc, :created_at.desc) 
  
  field :location
  field :music
  field :games
  field :food_drinks
  field :other
  field :stars,         type: Array, default: []
  field :star_count,    type: Integer, default: 0
  field :comment_count, type: Integer, default: 0  
  index({ id: 1})
  
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user
  attr_accessible :location, :music, :games, :food_drinks, :other, :stars
  validate :valid_suggestion
  
  def star(user)
    self.stars.include?(user.id) ? self.stars.delete(user.id) : self.stars << user.id
    self.star_count = self.stars.count
    self.save
    self.star_count
  end
    
  private
  
    def valid_suggestion
      strip_whitespace_and_tags
      
      unless self.location || self.music || self.games || self.food_drinks || self.other
        errors.add :base, "One of the fields must be filled out."  
      end
    end
    
    def strip_whitespace_and_tags
      if self.location
        self.location = strip_tags(self.location.strip)
        if self.location.empty?
          self.location = nil
        end
      end

      if self.music
        self.music = strip_tags(self.music.strip)
        if self.music.empty?
          self.music = nil
        end
      end

      if self.games
        self.games = strip_tags(self.games.strip)
        if self.games.empty?
          self.games = nil
        end
      end

      if self.food_drinks
        self.food_drinks = strip_tags(self.food_drinks.strip)
        if self.food_drinks.empty?
          self.food_drinks = nil
        end
      end

      if !self.other.nil?
        self.other = strip_tags(self.other.strip)
        if self.other.empty?
          self.other = nil
        end
      end
    end  
end

komanda/app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_filter :logged_in, except: [:index, :popular]
  before_filter :suggestions_count, only: [:index, :new, :create, :destroy]
  before_filter :new_suggestion, only: [:index, :popular, :new]
  before_filter :suggestion, only: [:star, :destroy]
  before_filter :store_url
  
  def suggestion
    @suggestion = Suggestion.find(params[:id])
  end
  
  def new_suggestion
    @suggestion = Suggestion.new
  end
  
  def suggestions_count
    @count = Suggestion.count
  end
    
  def index
    @upcoming = Event.upcoming
    @past     = Event.past
    @suggestions = Suggestion.recent
  end
  
  def popular
    @suggestions = Suggestion.popular
  end
  
  def new
  end
  
  def create
    @suggestion = current_user.suggestions.create(params[:suggestion])
    
    respond_to do |format|
      if @suggestion.valid?
        format.html { redirect_to suggestions_path}
      else
        format.html { render "new" }
      end
      format.js
    end
  end
  
  def destroy
    if authenticated_user?(@suggestion)
      @suggestion.destroy
    else
      redirect_to root_path
    end
  end
    
  def star
    @count = @suggestion.star(current_user)
  end

end

komanda/app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

komanda/app/views/suggestions/_comments_votes.html.erb
<div class="suggestion-stats muted">
	
	<% if current_user %>
		<%= link_to star_suggestion_path(suggestion), class: "star", 
			id: "star-link-#{suggestion.id}", remote: true do %>
			<%= image_tag(suggestion.stars.include?(current_user.id) ? "star.png" : "star_empty.png") %>
		<% end %>		
		
	<% else %>
		<%= link_to image_tag("star.png"), signin_path %>
	<% end %>
	<span id="star-count-<%= suggestion.id %>"><%= suggestion.stars.count %></span>
	| 
	<span id="comment-toggle-container-<%= suggestion.id %>">
		<% if suggestion.comments.count > 0 %>
			<%= link_to	suggestion_comments_path(suggestion), 
				class: "comment-toggle",
				id: "comment-toggle-#{suggestion.id}",
				"data-toggle" => "collapse", 
				"data-target" => "#comments-#{suggestion.id}", 
				remote: true do %>
					<span id="comments-count-<%= suggestion.id %>">
						<%= pluralize(suggestion.comments.count, "Comment") %>
			<% end %>		
		<% else %>
			<%= link_to	"#", class: "comment-toggle",
				id: "comment-toggle-#{suggestion.id}",
				"data-toggle" => "collapse", 
				"data-target" => "#comments-#{suggestion.id}" do %>
				<span id="comments-count-<%= suggestion.id %>">Comment</span>
			<% end %>
		<% end %>
	</span>
</div>

komanda/app/views/suggestions/_form.html.erb
<% if @count > 0 %>
	<%= form_for @suggestion, html: { class: "form-horizontal default hidden-phone" }, 
		remote: true do |f| %>

		<h3 class="center">
			New Suggestion
		</h3>

		<div class="alert alert-error center hide" id="suggestion-error">
			<i class="icon-exclamation-sign"></i> At least one of the fields must be filled out.
		</div>

		<div class="control-group">
			<div class="control-label"><%= f.label :location %></div>
			<div class="controls">
				<%= f.text_field :location, class: "input-large" %>
			</div>
		</div>

		<div class="control-group">
			<div class="control-label"><%= f.label :music %></div>
			<div class="controls">
				<%= f.text_field :music, class: "input-large" %>
			</div>
		</div>


		<div class="control-group">
			<div class="control-label"><%= f.label :games %></div>
			<div class="controls">
				<%= f.text_field :games, class: "input-large" %>
			</div>
		</div>

		<div class="control-group">
			<div class="control-label"><%= f.label :food_drinks, "Food/Drinks" %></div>
			<div class="controls">
				<%= f.text_field :food_drinks, class: "input-large" %>
			</div>
		</div>

		<div class="control-group">
			<div class="control-label"><%= f.label :other %></div>
			<div class="controls">
				<%= f.text_field :other, class: "input-large" %>
			</div>
		</div>

		<div class="controls">
	    <%= f.submit "Post", class: "btn btn-primary", id: "submit" %>
			<button class="btn btn-primary hide" id="dummy-button">
				<i class="icon-spinner icon-spin"></i></button>

	    <%= link_to "Cancel", suggestions_path, class: "btn" %>
		</div>
	<% end %>
	
	<%= form_for @suggestion, html: { class: "form-horizontal default visible-phone" } do |f| %>

		<h3 class="center">
			New Suggestion
		</h3>

		<% if @suggestion.errors.count > 0 %>
			<div class="alert alert-error center" id="suggestion-error">
				<i class="icon-exclamation-sign"></i> At least one of the fields must be filled out.
			</div>
		<% end %>

		<div class="control-group">
			<div class="control-label"><%= f.label :location %></div>
			<div class="controls">
				<%= f.text_field :location, class: "input-large" %>
			</div>
		</div>

		<div class="control-group">
			<div class="control-label"><%= f.label :music %></div>
			<div class="controls">
				<%= f.text_field :music, class: "input-large" %>
			</div>
		</div>


		<div class="control-group">
			<div class="control-label"><%= f.label :games %></div>
			<div class="controls">
				<%= f.text_field :games, class: "input-large" %>
			</div>
		</div>

		<div class="control-group">
			<div class="control-label"><%= f.label :food_drinks, "Food/Drinks" %></div>
			<div class="controls">
				<%= f.text_field :food_drinks, class: "input-large" %>
			</div>
		</div>

		<div class="control-group">
			<div class="control-label"><%= f.label :other %></div>
			<div class="controls">
				<%= f.text_field :other, class: "input-large" %>
			</div>
		</div>

		<div class="controls">
	    <%= f.submit "Post", class: "btn btn-primary", id: "submit" %>
			<button class="btn btn-primary hide" id="dummy-button">
				<i class="icon-spinner icon-spin"></i></button>

	    <%= link_to "Cancel", suggestions_path, class: "btn" %>
		</div>
	<% end %>
	
<% else %>
	<%= form_for @suggestion, html: { class: "form-horizontal default" } do |f| %>

		<h3 class="center">
			New Suggestion
		</h3>
		<% if @suggestion.errors.count > 0 %>
			<div class="alert alert-error center" id="suggestion-error">
				<i class="icon-exclamation-sign"></i> At least one of the fields must be filled out.
			</div>
		<% end %>

		<div class="control-group">
			<div class="control-label"><%= f.label :location %></div>
			<div class="controls">
				<%= f.text_field :location, class: "input-large" %>
			</div>
		</div>

		<div class="control-group">
			<div class="control-label"><%= f.label :music %></div>
			<div class="controls">
				<%= f.text_field :music, class: "input-large" %>
			</div>
		</div>


		<div class="control-group">
			<div class="control-label"><%= f.label :games %></div>
			<div class="controls">
				<%= f.text_field :games, class: "input-large" %>
			</div>
		</div>

		<div class="control-group">
			<div class="control-label"><%= f.label :food_drinks, "Food/Drinks" %></div>
			<div class="controls">
				<%= f.text_field :food_drinks, class: "input-large" %>
			</div>
		</div>

		<div class="control-group">
			<div class="control-label"><%= f.label :other %></div>
			<div class="controls">
				<%= f.text_field :other, class: "input-large" %>
			</div>
		</div>

		<div class="controls">
	    <%= f.submit "Post", class: "btn btn-primary", id: "submit" %>
			<button class="btn btn-primary hide" id="dummy-button">
				<i class="icon-spinner icon-spin"></i></button>

	    <%= link_to "Cancel", suggestions_path, class: "btn" %>
		</div>
	<% end %>
	
<% end %>

komanda/app/views/suggestions/_modal.html.erb
<div id="suggestion-modal" class="modal fade hide" data-keyboard="true">
	
	<div class="modal-header">
		<button type="button" class="close modal-close" data-dismiss="modal" aria-hidden="true">×</button>
		<h3 class="center">New Suggestion</h3>
	</div>
	
	<%= form_for @suggestion, html: { class: "form-horizontal default" }, remote: true do |f| %>
		<div class="modal-body">

			<div class="alert alert-error center hide" id="suggestion-error">
				<i class="icon-exclamation-sign"></i> At least one of the fields must be filled out.
			</div>

			<div class="control-group">
				<div class="control-label"><%= f.label :location %></div>
				<div class="controls">
					<%= f.text_field :location, class: "input-xlarge" %>
				</div>
			</div>

			<div class="control-group">
				<div class="control-label"><%= f.label :music %></div>
				<div class="controls">
					<%= f.text_field :music, class: "input-xlarge" %>
				</div>
			</div>


			<div class="control-group">
				<div class="control-label"><%= f.label :games %></div>
				<div class="controls">
					<%= f.text_field :games, class: "input-xlarge" %>
				</div>
			</div>

			<div class="control-group">
				<div class="control-label"><%= f.label :food_drinks, "Food/Drinks" %></div>
				<div class="controls">
					<%= f.text_field :food_drinks, class: "input-xlarge" %>
				</div>
			</div>

			<div class="control-group">
				<div class="control-label"><%= f.label :other %></div>
				<div class="controls">
					<%= f.text_field :other, class: "input-xlarge" %>
				</div>
			</div>
			
			<div class="controls">
		    <%= f.submit "Post", class: "btn btn-primary", id: "submit" %>
				<button class="btn btn-primary hide" id="dummy-button">
					<i class="icon-spinner icon-spin"></i></button>
		    <button class="btn" data-dismiss="modal"> Cancel</button>
			</div>
		</div>
	<% end %>
</div>

komanda/app/views/suggestions/_sort.html.erb
<% if @suggestions.count > 3 %>
	<div class="dropdown" id="_sort">
	  <%= link_to "#", class: "dropdown-toggle" do %>
			Sort (<span id="sort">recent</span>)<span class="caret"></span>
		<% end %>
	
	  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
	    <li>
	    	<%= link_to suggestions_path, id: "recent", remote: true do %>
					<i class="icon-check"></i>Recent
				<% end %>
	    </li>
			<li>
				<%= link_to popular_suggestions_path, id: "popular", remote: true do %>
					<i class="icon-check-empty"></i>Popular
				<% end %>
			</li>
	  </ul>
	</div>
<% end %>

komanda/app/views/suggestions/_suggestion.html.erb
<article id="<%= dom_id suggestion %>" class="default suggestion">
	<div class="media">
		<% if authenticated_user?(suggestion) %>
			<%= link_to "×", suggestion, 
				class: "close", 
				"rel"=>"tooltip",
				"title"=>"Delete",
				method: :delete, remote: true %>
		<% end %>
		
		
	  <%= link_to image_tag(suggestion.user.image_url, class: "media-object"),
	 				suggestion.user.profile_url, 
					class: "pull-left", 
					target: "_blank" %>
	  
		<div class="media-body">
			
	    <p class="media-heading">
				<%= link_to suggestion.user.name, suggestion.user.profile_url, target: "_blank" %>
				<span class="muted"><%= time_ago_in_words(suggestion.created_at) %></span>
			</p>
	    
			<table>
				
				<% if suggestion.location %>
					<tr>
						<td><i class="icon-map-marker"></i></td>
						<td><%= suggestion.location %></td>
					</tr>
				<% end %>
				
				
				<% if suggestion.music %>
					<tr>
						<td><i class="icon-music"></i></td>
						<td><%= suggestion.music %></td>
					</tr>
				<% end %>
				
				
				<% if suggestion.games %>
					<tr>
						<td><i class="icon-star"></i></td>
						<td><%= suggestion.games %></td>
					</tr>
				<% end %>
				
				
				<% if suggestion.food_drinks %>
					<tr>
						<td><i class="icon-beer"></i></td>
						<td><%= suggestion.food_drinks %></td>
					</tr>
				<% end %>
				
				
				<% if suggestion.other %>
					<tr>
						<td><i class="icon-info-sign"></i></td>
						<td><%= suggestion.other %></td>
					</tr>
				<% end %>
			</table>
	
	  </div>
	</div>
	
	<%= render 'comments_votes', suggestion: suggestion %>
	
	<div class="collapse" id="comments-<%= suggestion.id %>">

		<% if suggestion.comments.count > 0 %>
			<div class="loading-comments center hide" id="loading-comments-<%= suggestion.id %>">
				<i class="icon-spinner icon-large icon-spin"></i></div>
			<div class="comments" id="suggestion-comments-<%= suggestion.id %>"></div>
		<% else %>
			<div class="comments" id="suggestion-comments-<%= suggestion.id %>"></div>
		<% end %>

		<%= render 'comments/form', commentable: suggestion %>
	</div>
	
</article>

komanda/app/views/suggestions/create.js.erb
function clean_up() {
	$("#suggestion-modal").modal('hide')
	$("#suggestion-error").hide()
	$("#new_suggestion input").val("")
	$("#submit").val("Post")
}

function fix_comment_toggle(id) {
	$(id + " .comment-toggle").click(function(e) { e.preventDefault() })
}

function fix_star_link(id) {
	$(id).click(function() {
		star = $(this).find("img").first()
		if ($(star).attr("src") == "/assets/star.png") {
			$(star).attr("src", "/assets/star_empty.png")
		} else {
			$(star).attr("src", "/assets/star.png")
		}
	})
}

<% if @suggestion.errors.count > 0 %>
	$("#suggestion-error").slideDown()
<% else %>
	$("#suggestions-count").text("<%= @count + 1 %>")
	$("#suggestions").prepend("<%= escape_javascript (render @suggestion) %>")
	$("#<%= dom_id @suggestion %>").effect("highlight", {color: '#FCF8E3'}, 2000)	
	fix_comment_toggle("#<%= dom_id @suggestion %>")
	fix_star_link("#star-link-<%= @suggestion.id %>")
	clean_up()
<% end %>	

$("#submit").toggle()
$("#dummy-button").toggle()

komanda/app/views/suggestions/destroy.js.erb
$("#suggestions-count").text("<%= @count - 1 %>")
$("#<%= dom_id @suggestion %>").slideUp(function() { $("#<%= dom_id @suggestion %>").remove() })

komanda/app/views/suggestions/index.html.erb
<div class="row">
	<div class="pull-right facebook" style="width: 90px; height: 30px">
		<div class="fb-like" data-send="false" 
			data-layout="button_count" data-width="450" data-show-faces="true"></div>
	</div>
	
	<div class="span7">
		
		<p class="lead center">
			Have a great idea for a party but too busy to organize it all on your own?
			Suggest the party here and we	just might make it a reality!
		</p>
		
		<p class="center">
			<% if current_user %>
				<% if @suggestions.count > 0 %>
					<button class="btn btn-primary btn-large hidden-phone" 
						data-target="#suggestion-modal" data-toggle="modal" data-keyboard="true">
						Suggest</button>
				
					<%= link_to "Suggest", new_suggestion_path, 
						class: "btn btn-primary btn-large visible-phone" %>
					
				<% else %>
					<button id="suggestion-button" class="btn btn-primary btn-large hidden-phone hide" 
						data-target="#suggestion-modal" data-toggle="modal" data-keyboard="true">
						Suggest</button>
						
					<%= render 'form' %>
				<% end %>
			<% else %>
				<%= link_to "Suggest", signin_path, class: "btn btn-primary btn-large hidden-phone" %>
				<%= link_to "Suggest", signin_path, class: "btn btn-primary btn-large visible-phone" %>
			<% end %>
		</p>
			
		<% if @suggestions.count > 0 %>
			
			<div class="separator"></div>
			
			<div class="row">
				<div class="span3">
					<h4>Suggestions (<span id="suggestions-count"><%= @suggestions.count %></span>)</h4>
				</div>
				
				<div class="pull-right">
					<%= render 'sort' %>
				</div>
			</div>
			
			<div class="suggestions-container">
				<div class="center sort-loading"><i class="icon-spinner icon-spin icon-3x"></i></div>
				<div id="suggestions">
					<%= render @suggestions %>
				</div>
			</div>
		<% end %>
		
	</div>
	
	<aside class="offset1 span4 event-navbar">
		<%= render "events/event_full_nav" %>
	</aside>
</div>

<%= render 'modal' %>

komanda/app/views/suggestions/index.js.erb
$("#suggestions").html("<%= escape_javascript(render @suggestions) %>")
fix_star_links()
fix_comment_loading_effect()
fix_comment_toggle()
remove_loading_effect()

function fix_star_links() {
	$(".star").click(function() {
		star = $(this).find("img").first()
		if ($(star).attr("src") == "/assets/star.png") { 
			$(star).attr("src", "/assets/star_empty.png") 
		} else {
			$(star).attr("src", "/assets/star.png")
		}
	})
}

function remove_loading_effect() {
	$(".sort-loading").hide()
	$("#suggestions").css("opacity", 1)
}

function fix_comment_loading_effect() {
	$(".post-comment").click(function() {
		$(this).hide().next().show()
	})
}

function fix_comment_toggle() {
	$(".comment-toggle").click(function(e) {
		e.preventDefault()
		$(this).parent().parent().siblings().find(".loading-comments").first().show()
	})
}

komanda/app/views/suggestions/new.html.erb
<div class="row">
	<div class="offset3 span6">
		<%= render 'form' %>
	</div>
</div>

komanda/app/views/suggestions/popular.js.erb
$("#suggestions").html("<%= escape_javascript(render @suggestions) %>")
fix_star_links()
fix_comment_loading_effect()
fix_comment_toggle()
remove_loading_effect()

function fix_star_links() {
	$(".star").click(function() {
		star = $(this).find("img").first()
		if ($(star).attr("src") == "/assets/star.png") { 
			$(star).attr("src", "/assets/star_empty.png") 
		} else {
			$(star).attr("src", "/assets/star.png")
		}
	})
}

function remove_loading_effect() {
	$(".sort-loading").hide()
	$("#suggestions").css("opacity", 1)
}

function fix_comment_loading_effect() {
	$(".post-comment").click(function() {
		$(this).hide().next().show()
	})
}

function fix_comment_toggle() {
	$(".comment-toggle").click(function(e) {
		e.preventDefault()
		$(this).parent().parent().siblings().find(".loading-comments").first().show()
	})
}

komanda/app/views/suggestions/star.js.erb
$("#star-count-<%= @suggestion.id %>").text("<%= @count %>")
console.log("<%= @count %>")