komanda/config/routes.rb
Komanda::Application.routes.draw do

  root :to => 'events#index'
  
  resources :events do
    get :going, on: :member
    get :join, on: :member
    get :rate, on: :member
    get :pictures, on: :member
    resources :comments
  end
  
  resources :suggestions do
    get :star, on: :member
    get :popular, on: :collection
    resources :comments
  end
  
  resources :shares
  
  resources :orders
  
  resources :products
  
  match '/k-stuff' => 'products#index', as: :kstuff
  match '/k-stuff/new' => 'products#new'
  match '/contact' => 'static_pages#contact', as: :contact
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'parties#index'
  match '/signin' => 'sessions#new', as: :signin
  match '/signout' => 'sessions#destroy', as: :signout
end

komanda/app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::MultiParameterAttributes
  
  default_scope     desc(:date)
  scope :upcoming,  where(:date.gte => Date.current())
  scope :past,      where(:date.lt => Date.current())
  
  field :name,        type: String
  field :date,        type: Date, default: Date.current()
  field :time,        type: Time, default: Time.now
  field :flyer,       type: String
  field :preview,     type: String
  field :description, type: String
  field :address,     type: String
  field :map_link,    type: String
  field :price,       type: Float, default: 15.00
  field :views,       type: Integer, default: 0
  field :pictures,    type: Array, default: []
  field :ratings,     type: Hash, default: {}
  field :tickets,     type: Hash, default: {}
  field :_id,         type: String, default: ->{ name }
  
  index({ id: 1})
  has_many :comments, as: :commentable, dependent: :destroy
  has_and_belongs_to_many :users
  validates_presence_of :name, :date, :time, :flyer, :description, :address
  
  def upcoming?
    self.date >= Date.current()
  end
  
  def join(user, reseeding)
    if upcoming? || reseeding
      self.users << user unless self.users.include?(user)
    end
  end
  
  def rating
    if self.ratings.empty?
      return 0
    else
      avg = 0
      self.ratings.each_value do |value|
        avg += value.to_i
      end

      return avg / self.ratings.count.to_i
    end
  end
  
  def tickets_sold
    total = 0
    self.tickets.values.each do |v|
      total += v
    end
    total
  end
end

komanda/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :admin_user, only: [:new, :create, :edit, :update, :destroy]
  before_filter :logged_in, only: [:join, :rate]
  before_filter :find_event, only: [:show, :edit, :update, :destroy, :pictures, :join, :rate, :going]
  before_filter :increment_views, only: :show
  before_filter :get_upcoming_and_past_event, only: [:show, :index]
  before_filter :store_url
  
  def find_event
    @event = Event.find(params[:id])
  end
  
  def get_upcoming_and_past_event
    @upcoming = Event.upcoming
    @past     = Event.past
  end
  
  def increment_views
    @event.inc(:views, 1)
  end
    
  def index
  end
  
  def show
    count = @event.users.count
    
    if count > 8
      @going = @event.users.skip(count - 8)
    else
      @going = @event.users
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(params[:event])
    @event.pictures = (params[:event][:pictures]).split
    
    if @event.save
      redirect_to @event
    else
      render "new"
    end
  end
  
  def edit
  end

  def update
    @event.update_attributes(params[:event])
    @event.update_attribute(:pictures, (params[:event][:pictures]).split)
    redirect_to @event, notice: "Event updated!"
  end

  def destroy
    @event.destroy
    redirect_to root_path
  end
  
  def join
    @event.join(current_user, false)

    render json: { count:       @event.users.count, 
                   name:        current_user.name,
                   image_url:   current_user.image_url,
                   profile_url: current_user.profile_url }
  end
  
  def pictures
  end
  
  def rate
    @event.ratings["#{current_user.id}"] = params[:rating].to_i
    @event.save
    
    render json: { new_rating:  @event.rating,
                   count:       @event.ratings.count }
  end
  
  def going
    @going = @event.users
  end
end

komanda/app/helpers/events_helper.rb
module EventsHelper
  def thumb_url(url)
    # http://imageshack.us/a/img717/8971/image7xd.jpg - URL
    # http://imageshack.us/scaled/thumbx2/717/image7xd.jpg - thumb
    if (url.include?("/scaled/"))
      tokens = url.split("/")
      tokens[4] = "thumbx2"
      return tokens.join("/")
    else  
      tokens = url.split("/")
      return "http://imageshack.us/scaled/thumbx2/#{tokens[4].slice(3, tokens[4].length)}/#{tokens[6]}"
    end
  end
end

komanda/app/views/events/_controlls.html.erb
<div class="default controlls">
	<%= link_to edit_event_path(@event) do %>
		<i class="icon-edit"></i> Edit
	<% end %> 
	<%= link_to @event,
				method: :delete, 
				:data => { :confirm => 'Are you sure you want to delete this event?' } do %>
		<i class="icon-trash"></i> Delete
	<% end %>
	
	<div class="separator"></div>
	
	<p><span class="muted">Views:</span> <strong><%= @event.views %></strong></p>
	<p><span class="muted">Tickets:</span> <strong><%= @event.tickets_sold %></strong></p>
</div>

komanda/app/views/events/_event_full.html.erb
<% if notice %>
	<div class="alert alert-success">
		<%= notice %>
	</div>
<% end %>

<h2>
	<%= @event.name %>
	<div class="pull-right facebook" style="width: 90px; height: 30px">
		<div class="fb-like" data-send="false" 
			data-layout="button_count" data-width="450" data-show-faces="true"></div>
	</div>
</h2>

<div class="separator"></div>

<table>
	<tr>
		<td class="icon"><i class="icon-calendar"></i></td>
		<td>
			<%= time_tag @event.date, format: "%B %e" %>, 
			<%= time_tag @event.time, format: "%l:%M %P" %>
		</td>
	</tr>
	
	<tr>
		<td><i class="icon-map-marker"></i></td>	
		<td><%= link_to @event.address, @event.map_link, target: "_blank" %></td>
	</tr>
	
	<tr>
		<td><i class="icon-info-sign"></td>	
		<td><%= raw @event.description %></td>
	</tr>
	
	<tr>
		<td><i class="icon-comments"></i></td>
		<td>			
			<strong id="comment-count"><%= pluralize @event.comments.count, "Comment" %></strong>
		</td>
	</tr>
</table>

<div id="comments">
	<%= render @event.comments, commentable: @event %>
</div>
<%= render "comments/form", commentable: @event %>

komanda/app/views/events/_event_full_nav.html.erb
<div>
	<% if @upcoming.count > 0 %>
		<h4 class="left">Upcoming event</h4>
		
		<% @upcoming.each do |e| %>
			<% if e == @event %>
				<div class="media default">
					<%= image_tag e.flyer, class: "media-object pull-left", size: "40x40" %>

					<div class="media-body">
				    <h6 class="media-heading">
				    	<%= e.name %>
				    </h6>
						<small class="muted"><%= time_tag e.date, format: "%B %e"%></small>
				  </div>
				</div>
			<% else %>
				<%= link_to e do %>
					<div class="media">
						<%= image_tag e.flyer, class: "media-object pull-left", size: "40x40" %>

						<div class="media-body">
					    <h6 class="media-heading">
					    	<%= e.name %>
					    </h6>
							<small class="muted"><%= time_tag e.date, format: "%B %e"%></small>
					  </div>
					</div>
				<% end %>
			<% end %>
		<% end %>
		
	<% end %>	
	
	<h4>Past events</h4>
			
	<% @past.each do |e| %>
		<% if e == @event %>
			<div class="media default">
				<%= image_tag e.flyer, class: "media-object pull-left", size: "40x40" %>

				<div class="media-body">
			    <h6 class="media-heading">
			    	<%= e.name %>
			    </h6>
					<small class="muted"><%= time_tag e.date, format: "%B %e"%></small>
			  </div>
			</div>
		<% else %>
			<%= link_to e do %>
				<div class="media">
					<%= image_tag e.flyer, class: "media-object pull-left", size: "40x40" %>

					<div class="media-body">
				    <h6 class="media-heading">
				    	<%= e.name %>
				    </h6>
						<small class="muted"><%= time_tag e.date, format: "%B %e"%></small>
				  </div>
				</div>
			<% end %>
		<% end %>
	<% end %>
	
</div>

komanda/app/views/events/_form.html.erb
<%= form_for @event, html: { class: "form-horizontal" } do |f| %>
	
	<% if @event.errors.count > 0 %>
		<div class="alert alert-error">
			<% @event.errors.full_messages.each do |error| %>
				<p><%= error %></p>
			<% end %>
		</div>
	<% end %>
	
	<div class="control-group">
		<div class="control-label"><%= f.label :name %></div>
		<div class="controls">
			<%= f.text_field :name %>
		</div>
	</div>
	
	<div class="control-group">
		<div class="control-label"><%= f.label :date, "Date/Time" %></div>
		<div class="controls">
			<%= f.text_field :date, class: "date-picker" %> 
			<%= f.time_select :time, ampm: true, minute_step: 15 %>
		</div>
	</div>
	
	<div class="control-group">
		<div class="control-label"><%= f.label :flyer %></div>
		<div class="controls">
			<%= f.text_field :flyer %>
		</div>
	</div>
	
	<div class="control-group">
		<div class="control-label"><%= f.label :preview %></div>
		<div class="controls">
			<%= f.text_area :preview, rows: 3 %>
		</div>
	</div>
		
	<div class="control-group">
		<div class="control-label"><%= f.label :description %></div>
		<div class="controls">
			<%= f.text_area :description, rows: 3 %>
		</div>
	</div>	
	
	<div class="control-group">
		<div class="control-label"><%= f.label :address %></div>
		<div class="controls">
			<%= f.text_area :address, rows: 3 %>
		</div>
	</div>
		
	<div class="control-group">
		<div class="control-label"><%= f.label :map_link %></div>
		<div class="controls">
			<%= f.text_field :map_link %>
		</div>
	</div>	
	
	<div class="control-group">
		<div class="control-label"><%= f.label :price %></div>
		<div class="controls">
			<%= f.text_field :price %>
		</div>
	</div>
	
	<div class="control-group">
		<div class="control-label"><%= f.label :pictures %></div>
		<div class="controls">
			<%= f.text_area :pictures, rows: 3, value: @event.pictures.join(' ') %>
		</div>
	</div>
		
	<div class="separator"></div>
	
	<div class="controls">
		<% if params[:action] == "new" %>
			<%= f.submit "Create", class: "btn btn-primary" %>			
		<% else %>
			<%= f.submit "Update", class: "btn btn-primary" %>
		<% end %>

		<%= link_to "Cancel", root_path, class: "btn" %>
	</div>
<% end %>

komanda/app/views/events/_going_preview.html.erb
<div class="default">
	<% if @event.upcoming? %>
		<% if current_user %>
			<% if @event.users.include?(current_user) %>
				<%= link_to "Going", "#", 
						class: "btn btn-success disabled", 
						id: "join",
						remote: true %>
			<% else %>
				<%= link_to "Join", 
						join_event_path, 
						class: "btn btn-success", 
						id: "join" %>
			<% end %>
		<% else %>
			<%= link_to "Join", signin_path, class: "btn btn-success" %>
		<% end %>
		<div class="separator"></div>
	<% end %>
	
	<p class="alert alert-error hide" id="error">
		<i class="icon-exclamation-sign"></i>
		Oops, something went wrong. Try reloading the page.
	</p>
	
	<p class="lead muted">
		Going (<span id="going-count"><%= @event.users.count %></span>):
	</p>
	
	<ul class="unstyled clearfix" id="going">
		<% @going.each do |user| %>
			<li rel="tooltip" title="<%= user.name %>">
				<%= link_to image_tag(user.image_url), 
					user.profile_url, 
					target: "_blank" %>
			</li>
		<% end %>
	</ul>
	
	<% if @going.count > 8 %>
		<p>
			<%= link_to "See all", 
					going_event_path(@event),
					class: "hidden-phone",
					"data-target" => "#going-modal",
					"data-toggle" => "modal",
					remote: true
			%>
			
			<%= link_to "See all", 
					going_event_path(@event),
					class: "visible-phone"
			%>
		</p>
		
		<%= render 'modal' %>
	<% end %>
	
</div>

komanda/app/views/events/_pictures_preview.html.erb
<div class="default clearfix">
	<p class="lead muted">Pictures (<%= @event.pictures.count %>)</p>
	
	<div id="pictures-sidebar">
		<% if @event.pictures.count <= 9 %>

			<% @event.pictures.each do |picture| %>
				<%= link_to (image_tag (thumb_url picture)), pictures_event_path(@event) %>
			<% end %>

		<% else %>
			<% for i in 0..8 %>
				<%= link_to (image_tag (thumb_url @event.pictures[i])), pictures_event_path(@event) %>
			<% end %>
		<% end %>
	</div>
	
	<% if @event.pictures.count > 9 %>
		<p>
			<%= link_to "See all", pictures_event_path(@event) %>
		</p>
	<% end %>
</div>

komanda/app/views/events/_rating.html.erb
<div class="default">
	<p class="lead muted">
		Ratings (<span id="ratings-count"><%= @event.ratings.count %></span>)
	</p>
	
	<div class="alert alert-error hide" id="rating-error">
		<i class="icon-exclamation-sign"></i> Oops, something went wrong. Try reloading the page.
	</div>
	<div class="rating">
		<% if current_user %>				
				<div id="rate" val="<%= @event.rating %>">
					<% for i in 1..@event.rating %>
						<%= link_to image_tag("star.png", size: "35x0"),
							"#{rate_event_path(@event)}?rating=#{i}" %>
					<% end -%>

					<% for i in 1 + @event.rating..5 %>
						<%= link_to image_tag("star_empty.png", size: "35x0"), 
							"#{rate_event_path(@event)}?rating=#{i}" %>
					<% end -%>
				</div> 
		<% else %>
			
			<%= link_to signin_path do  %>
					<% for i in 1..@event.rating %>
						<%= image_tag("star.png", size: "35x0") %>
					<% end -%>

					<% for i in 1 + @event.rating..5 %>
						<%= image_tag("star_empty.png", size: "35x0") %>
					<% end -%> 
				</a>
			<% end %>
			
		<% end -%>
		
		<i class='icon-spinner icon-spin icon-large' id="rating-loading"></i>
		
	</div>
</div>

komanda/app/views/events/_upcoming.html.erb
<article class="default upcoming-event">
	<div class="row">
		<div class="span3">
			<%= link_to image_tag(event.flyer), event %>
		</div>
		
		<div class="span8">
			<h3><%= event.name %>
				<small>
					
				</small>	
			</h3>
			
			<div class="separator"></div>
			
			<table>
				<tr>
					<td class="icon"><i class="icon-calendar"></i></td>
					<td>
						<%= time_tag event.date, format: "%B %e" %>, 
						<%= time_tag event.time, format: "%l:%M %P" %>
					</td>
				</tr>

				<tr>
					<td><i class="icon-map-marker"></i></td>	
					<td><%= link_to event.address, event.map_link, target: "_blank" %></td>
				</tr>

				<tr>
					<td><i class="icon-info-sign"></td>	
					<td>
						<%= raw event.preview %>
						<%= link_to "Continue...", event %>
					</td>
				</tr>
			</table>
			
			<div class="separator"></div>
			
			<% if current_user %>
				<%= link_to "Buy ticket", "#{new_order_path}?event_id=#{event.id}", class: "btn btn-primary" %>
			<% else %>
				<%= link_to "Buy ticket", signin_path, class: "btn btn-primary" %>
			<% end %>
			
			<%= link_to "#{event_path(event)}#comments", class: "btn" do %>
				<i class="icon-comments"></i> Comment
			<% end %>
			
		</div>
	</div>
</article>

komanda/app/views/events/edit.html.erb
<div class="row">
	<div class="offset3 span6">
		<div class="default">
			<p class="lead center">
				Edit Event
			</p>
			<%= render "form" %>
		</div>
	</div>
</div>

komanda/app/views/events/going.js.erb
var going = ""

<%= @going.each do |user| %>
	going += "<%= escape_javascript(render user) %>"
<% end %>

$("#going-modal-effect").hide()
$("#_going").append(going)

komanda/app/views/events/index.html.erb
<h3>
	Upcoming Event
	<div class="pull-right facebook" style="width: 90px; height: 30px">
		<div class="fb-like" data-send="false" 
			data-layout="button_count" data-width="450" data-show-faces="true"></div>
	</div>
</h3>

<% if @upcoming.size > 0 %>
	<%= render 'upcoming', event: @upcoming.first %>
<% else %>
	<p class='lead'>
		We are planning our next event. Have a suggestion? 
		<%= link_to "Let us know!", suggestions_path %> Or <%= link_to "share an event", shares_path %>
		your are going to!
	</p>
	
	<% if admin_user? %>
		<div class="center">
			<%= link_to "New Event", new_event_path, class: "btn btn-primary btn-large" %>
		</div>
	<% end %>

<% end %>

<h3>Past Events</h3>
<div class="row">
	<%= render @past %>
</div>

komanda/app/views/events/new.html.erb
<h1>Events#new</h1>
<p>Find me in app/views/events/new.html.erb</p>

komanda/app/views/events/show.html.erb
<div class="row">
	
	<aside class="span3">
		<%= render "event_full_sidebar" %>
	</aside>
	
	<article class="span7 default">
		<%= render 'event_full' %>
	</article>
	
	<aside class="span2 event-navbar">
		<%= render "event_full_nav" %>
	</aside>
</div>

komanda/app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>