komanda/config/routes.rb
Komanda::Application.routes.draw do

  root :to => 'events#index'
  
  resources :events do
    get :going, on: :member
    get :join, on: :member
    get :rate, on: :member
    get :pictures, on: :member
    resources :comments
  end
  
  resources :suggestions do
    get :star, on: :member
    get :popular, on: :collection
    resources :comments
  end
  
  resources :shares
  
  resources :orders
  
  resources :products
  
  match '/k-stuff' => 'products#index', as: :kstuff
  match '/k-stuff/new' => 'products#new'
  match '/contact' => 'static_pages#contact', as: :contact
  
  match '/auth/:provider/callback' => 'sessions#create'
  match '/auth/failure' => 'parties#index'
  match '/signin' => 'sessions#new', as: :signin
  match '/signout' => 'sessions#destroy', as: :signout
end

komanda/app/views/layouts/_footer.html.erb
<footer id="footer">

	<div class="container">
		<%= link_to (image_tag "star_empty.png", size: "40x30"), root_path, class: "pull-right" %>
		
		<ul class="nav nav-pills">
			<li><%= link_to "Contact", "/contact" %> <span class="muted"></span>
			<li><a href="#donate-modal" data-toggle="modal" data-keyboard="true">Donate</a></li>
			<li><%= link_to "Events", events_path %></li>
			<li class="visible-desktop"><%= link_to "Suggestions", suggestions_path %></li>
			<li class="visible-desktop"><%= link_to "Shares", shares_path %></li>
		</ul>

		<div id="donate-modal" class="modal fade hide">
			<div class="modal-header center">
				<button type="button" class="close modal-close" 
					data-dismiss="modal" aria-hidden="true">×</button>
				<h3>Make a donation</h3>
			</div>
			<div class="modal-body center">
				<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
				<input type="hidden" name="cmd" value="_s-xclick">
				<input type="hidden" name="hosted_button_id" value="FUYG2NDH7AYC2">
				<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donateCC_LG.gif" 
					border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
				<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
				</form>
			</div>
		</div>
	</div>
	
</footer>

komanda/app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
			<%= link_to root_path, class: "brand" do %>
				<%= image_tag 'star.png', size: "40x40" %> komanda
			<% end %>
      <div class="nav-collapse collapse">
        <ul class="nav">
					<li class="<%= "active" if events_controller? %>">
						<%= link_to "Events", root_path %></li>
          <li class="<%= "active" if suggestions_controller? %>">
						<%= link_to "Suggestions", suggestions_path %></li>
					<li class="<%= "active" if shares_controller? %>">
						<%= link_to "Shares", shares_path %></li>
					<li class="<%= "active" if products_controller? %>">
						<%= link_to "K-stuff", kstuff_path %></li>
          <li><%= link_to "Contact", contact_path  %></li>
        </ul>
				<ul class="nav pull-right">
					<li>
						<% if current_user %>
							<%= link_to current_user.profile_url, target: "_blank" do %>
								<%= image_tag current_user.image_url, class: "profile-picture" %>
								<%= current_user.name %>
							<% end %>
						<% else %>
							<%= link_to "Sign in", signin_path %>
						<% end %>
					</li>
				</ul>
      </div>
    </div>
  </div>
</nav>

komanda/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Komanda</title>
	<meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  	<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
	<div id="wrap">
		<%= render "layouts/header" unless sessions_controller? %>
		<section class="container top">
			<%= yield %>
		</section>
		<div id="push"></div>
	</div>
	<%= render 'layouts/footer' unless sessions_controller? %>
	
</body>
</html>